version: '3'

volumes:
  mysql-data:

services:
  web-backend:
    build: ./config/backend
    container_name: web-backend
    ports:
      - 8080:80
    volumes:
      - ./sources:/var/www/html
      - ./config/backend/php.ini:/usr/local/etc/php/php.ini
      - ./config/httpd_security.conf:/etc/apache2/conf-available/security.conf
    working_dir: /var/www/html
    environment:
      APP_ENV: local
    depends_on:
      - web-mysql
    restart: always

  web-mysql:
    container_name: web-mysql
    image: "mysql:5.7.43"
    ports:
        - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  web-phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - web-mysql:mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: web-mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
